import html2pdf from 'html2pdf.js';
import { AgreementResponse } from '@/types/api';

export type BrandingOptions = {
    companyName?: string;
    address?: string;
    phone?: string;
    email?: string;
};

function formatMoney(amount: number | null | undefined): string {
    if (amount == null) return '-';
    return `₹${amount.toLocaleString('en-IN')}`;
}

const RESOURCES = {
    en: {
        documentTitle: 'TOUR BOOKING AGREEMENT',
        customerDetails: 'Customer Details',
        tripOverview: 'Trip Overview',
        busRates: 'Bus Rate Breakdown',
        paymentSummary: 'Payment Summary',
        notes: 'Special Notes',
        name: 'Name',
        contact: 'Contact',
        tripDate: 'Trip Date',
        places: 'Places',
        vehicle: 'Vehicle',
        passengers: 'Passengers',
        bus: 'Bus',
        description: 'Description',
        vehicleCol: 'Vehicle',
        perDayRentCol: 'Per Day Rent',
        mountainRentCol: 'Mountain Rent',
        perDayRent: 'Per Day Rent',
        mountainRent: 'Mountain Rent',
        totalAmount: 'Total Amount',
        advancePaid: 'Less: Advance Paid',
        balanceDue: 'Balance Due',
        customerSig: 'Customer Signature',
        authSig: 'Authorized Signatory',
        generatedBy: 'Generated by Tour Booking App on',
        termsHeader: 'Terms and Conditions',
        terms: [
            'This booking is subject to vehicle availability and confirmation.',
            'Advance payment is non-refundable in case of cancellation within 24 hours of departure.',
            'Toll, parking, and permit charges are excluded unless specified otherwise.',
            'Driver support (Batta) is included/excluded as per verbal agreement.',
            'Any damage to the vehicle by passengers will be charged accordingly.'
        ]
    }
};

function generateHtml(data: AgreementResponse, branding?: BrandingOptions): string {
    const R = RESOURCES.en;

    const companyName = branding?.companyName || '[YOUR COMPANY NAME]';
    const companyAddress = branding?.address || '';
    const companyPhone = branding?.phone || '-';
    const companyEmail = branding?.email || '';

    const busRatesRows = data.useIndividualBusRates && data.busRates
        ? (data.busRates || []).map((rate, i) => `
        <tr>
          <td>${R.bus} ${i + 1}</td>
          <td class="amount-col">${formatMoney(rate.perDayRent)}</td>
          <td class="amount-col">${rate.includeMountainRent ? formatMoney(rate.mountainRent) : '-'}</td>
        </tr>
      `).join('')
        : `
        <tr>
            <td style="font-style: italic;">${data.busType} (${data.busCount || 1})</td>
            <td class="amount-col">${formatMoney(data.perDayRent)}</td>
            <td class="amount-col">${data.includeMountainRent ? formatMoney(data.mountainRent) : '-'}</td>
        </tr>
    `;

    const termsHtml = R.terms.map(t => `<li>${t}</li>`).join('');

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${R.documentTitle}</title>
  <style>
    @page { margin: 40px; }
    body { 
      font-family: 'Helvetica Neue', 'Helvetica', sans-serif;
      font-size: 12px;
      line-height: 1.6;
      color: #333;
      margin: 0;
      padding: 0;
    }

    .container {
      padding: 0 10px;
    }

    .header {
      text-align: center;
      margin-bottom: 30px;
      border-bottom: 3px double #1a365d;
      padding-bottom: 20px;
    }
    .company-name {
      font-size: 26px;
      font-weight: 800;
      text-transform: uppercase;
      color: #1a365d;
      margin-bottom: 8px;
    }
    .company-details {
      font-size: 12px;
      color: #444;
      line-height: 1.4;
    }
    
    .doc-title {
      font-size: 20px;
      font-weight: 700;
      text-align: center;
      margin: 20px 0 30px 0;
      text-transform: uppercase;
      letter-spacing: 1px;
      border-bottom: 1px solid #ccc;
      display: inline-block;
      padding-bottom: 5px;
    }
    .doc-title-container { text-align: center; }

    .section {
      margin-bottom: 25px;
      page-break-inside: avoid;
    }
    .section-title {
      font-size: 14px;
      font-weight: 700;
      color: #1a365d;
      padding: 5px 0;
      border-bottom: 2px solid #e5e7eb;
      margin-bottom: 12px;
      text-transform: uppercase;
    }

    .flex-row {
      display: flex;
      justify-content: space-between;
      gap: 40px;
      page-break-inside: avoid;
      margin-bottom: 20px;
    }
    .flex-col {
      flex: 1;
    }

    .row {
      display: flex;
      margin-bottom: 8px;
      align-items: flex-start;
    }
    .label {
      font-weight: 600;
      width: 140px;
      color: #555;
      flex-shrink: 0;
    }
    .value {
      flex: 1;
      font-weight: 500;
      color: #000;
      word-wrap: break-word;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
      page-break-inside: avoid;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    th, td {
      border: 1px solid #e5e7eb;
      padding: 10px;
      text-align: left;
    }
    th {
      background-color: #f3f4f6;
      font-weight: 700;
      color: #374151;
      text-transform: uppercase;
      font-size: 11px;
    }
    .amount-col {
      text-align: right;
      font-family: 'Courier New', Courier, monospace;
    }

    .payment-box {
      border: 1px solid #e5e7eb;
      background-color: #f9fafb;
      padding: 15px;
      width: 320px;
      margin-left: auto;
      page-break-inside: avoid;
      border-radius: 4px;
    }
    .pay-row {
      display: flex;
      justify-content: space-between;
      margin-bottom: 8px;
    }
    .pay-row.total {
      border-top: 2px solid #d1d5db;
      padding-top: 8px;
      margin-top: 8px;
      font-weight: 800;
      font-size: 15px;
      color: #1a365d;
    }

    .footer-sigs {
      margin-top: 60px;
      display: flex;
      justify-content: space-between;
      gap: 60px;
      page-break-inside: avoid;
    }
    .signature-box {
      text-align: center;
      flex: 1;
    }
    .signature-line {
      border-top: 1px solid #000; 
      padding-top: 8px; 
      font-weight: 600; 
      font-size: 12px;
      margin-top: 50px;
    }

    .terms-and-signatures {
       page-break-inside: avoid;
       margin-top: 30px;
    }

    .terms {
      margin-top: 20px;
      margin-bottom: 40px;
      font-size: 10px;
      color: #666;
      border-top: 1px solid #e5e7eb;
      padding-top: 15px;
    }
    .terms h4 {
      margin-bottom: 8px;
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      color: #333;
    }
    .terms ul {
      padding-left: 18px;
      margin: 0;
    }
    .terms li {
      margin-bottom: 4px;
    }

    .meta-footer {
      text-align: center;
      margin-top: 40px;
      font-size: 9px;
      color: #9ca3af;
      border-top: 1px solid #f3f4f6;
      padding-top: 10px;
    }
  </style>
</head>
<body>
  <div class="container">
    
    <div class="header">
      <div class="company-name">${companyName}</div>
      <div class="company-details">
        ${companyAddress}<br/>
        ${R.contact}: ${companyPhone} ${companyEmail ? '| ' + companyEmail : ''}
      </div>
    </div>

    <div class="doc-title-container">
        <div class="doc-title">${R.documentTitle}</div>
    </div>

    <div class="flex-row">
      <div class="flex-col section">
        <div class="section-title">${R.customerDetails}</div>
        <div class="row"><span class="label">${R.name}:</span> <span class="value">${data.customerName}</span></div>
        <div class="row"><span class="label">${R.contact}:</span> <span class="value">${data.phone}</span></div>
        <div class="row"><span class="label">${R.passengers}:</span> <span class="value">${data.passengers || '-'}</span></div>
      </div>
      <div class="flex-col section">
         <div class="section-title">${R.tripOverview}</div>
         <div class="row"><span class="label">${R.tripDate}:</span> <span class="value">${data.fromDate} to ${data.toDate}</span></div>
         <div class="row"><span class="label">${R.places}:</span> <span class="value">${data.placesToCover}</span></div>
         <div class="row"><span class="label">${R.vehicle}:</span> <span class="value">${data.busType} x ${data.busCount || 1}</span></div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">${R.busRates}</div>
      <table>
         <tr>
           <th>${data.useIndividualBusRates ? R.vehicleCol : R.description}</th>
           <th class="amount-col">${data.useIndividualBusRates ? R.perDayRentCol : R.perDayRent}</th>
           <th class="amount-col">${data.useIndividualBusRates ? R.mountainRentCol : R.mountainRent}</th>
         </tr>
         ${busRatesRows}
      </table>
    </div>

    <div class="section">
      <div class="section-title">${R.paymentSummary}</div>
      <div class="payment-box">
         <div class="pay-row">
           <span>${R.totalAmount}:</span>
           <span>${formatMoney(data.totalAmount)}</span>
         </div>
         <div class="pay-row">
           <span>${R.advancePaid}:</span>
           <span>${formatMoney(data.advancePaid)}</span>
         </div>
         <div class="pay-row total">
           <span>${R.balanceDue}:</span>
           <span>${formatMoney(data.balance)}</span>
         </div>
      </div>
    </div>

    ${data.notes ? `
    <div class="section">
      <div class="section-title">${R.notes}</div>
      <p>${data.notes}</p>
    </div>` : ''}

    <div class="terms-and-signatures">
      <div class="terms">
        <h4>${R.termsHeader}</h4>
        <ul>
          ${termsHtml}
        </ul>
      </div>

      <div class="footer-sigs">
         <div class="signature-box">
           <div class="signature-line">${R.customerSig}</div>
         </div>
         <div class="signature-box">
           <div class="signature-line">${R.authSig}</div>
         </div>
      </div>
    </div>

    <div class="meta-footer">
      ${R.generatedBy} ${new Date().toLocaleDateString('en-IN')}
    </div>

  </div>
</body>
</html>
  `;
}

export async function generateAndDownloadPdf(
    data: AgreementResponse,
    branding?: BrandingOptions
): Promise<void> {
    try {
        const html = generateHtml(data, branding);

        // Create a temporary container
        const element = document.createElement('div');
        element.innerHTML = html;
        element.style.position = 'absolute';
        element.style.left = '-9999px';
        document.body.appendChild(element);

        const opt = {
            margin: 10,
            filename: `booking-${data.customerName.replace(/\s+/g, '-')}-${Date.now()}.pdf`,
            image: { type: 'jpeg' as const, quality: 0.98 },
            html2canvas: { scale: 2, useCORS: true },
            jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' as const }
        };

        await html2pdf().set(opt).from(element).save();

        // Clean up
        document.body.removeChild(element);
    } catch (error) {
        console.error('PDF generation error:', error);
        throw new Error('Failed to generate PDF');
    }
}
