import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Alert, Platform } from 'react-native';

import type { AgreementDraft } from '../types/agreement';
import type { AgreementResponse } from '../types/api';

export type BrandingOptions = {
  companyName?: string;
  address?: string;
  phone?: string;
  email?: string;
};

type AgreementData = {
  customerName: string;
  phone: string;
  fromDate: string;
  toDate: string;
  busType: string;
  busCount: string | number | null;
  passengers: string | number | null;
  placesToCover: string;

  perDayRent: string | number | null;
  includeMountainRent: boolean;
  mountainRent: string | number | null;

  totalAmount: string | number | null;
  advancePaid: string | number | null;
  balance: string | number | null;

  notes?: string;

  // For individual rates
  useIndividualBusRates: boolean;
  busRates?: Array<{
    perDayRent: string | number | null;
    includeMountainRent: boolean;
    mountainRent: string | number | null;
  }> | null;
};

// Normalize data from Response or Draft
function normalize(data: AgreementResponse | AgreementDraft): AgreementData {
  if ('id' in data) {
    // It's a Response
    return {
      customerName: data.customerName,
      phone: data.phone,
      fromDate: data.fromDate,
      toDate: data.toDate,
      busType: data.busType,
      busCount: data.busCount,
      passengers: data.passengers,
      placesToCover: data.placesToCover,
      perDayRent: data.perDayRent,
      includeMountainRent: data.includeMountainRent,
      mountainRent: data.mountainRent,
      totalAmount: data.totalAmount,
      advancePaid: data.advancePaid,
      balance: data.balance,
      notes: data.notes,
      useIndividualBusRates: data.useIndividualBusRates,
      busRates: data.busRates,
    };
  } else {
    // It's a Draft
    return {
      customerName: data.customerName,
      phone: data.phone,
      fromDate: data.fromDate,
      toDate: data.toDate,
      busType: data.busType,
      busCount: data.busCount,
      passengers: data.passengers,
      placesToCover: data.placesToCover,
      perDayRent: data.perDayRent,
      includeMountainRent: data.includeMountainRent,
      mountainRent: data.mountainRent,
      totalAmount: data.totalAmount,
      advancePaid: data.advancePaid,
      balance: data.balance,
      notes: data.notes,
      useIndividualBusRates: data.useIndividualBusRates,
      busRates: data.individualBusRates,
    };
  }
}

function formatMoney(amount: string | number | null | undefined): string {
  if (amount == null || amount === '') return '-';
  const n = Number(amount);
  if (Number.isNaN(n)) return String(amount);
  return '₹' + n.toLocaleString('en-IN');
}

const RESOURCES = {
  en: {
    companyName: '',
    regdNo: '',
    address: '',
    email: '',
    phoneLabel: 'Cell',
    documentTitle: 'TOUR BOOKING AGREEMENT',

    // Headers
    customerDetails: 'Customer Details',
    tripOverview: 'Trip Overview',
    busRates: 'Bus Rate Breakdown',
    paymentSummary: 'Payment Summary',
    notes: 'Special Notes',

    // Labels
    name: 'Name',
    contact: 'Contact',
    bookingDate: 'Booking Date',
    tripDate: 'Trip Date',
    places: 'Places',
    vehicle: 'Vehicle',
    passengers: 'Passengers',
    bus: 'Bus',
    description: 'Description', // Added

    // Table
    vehicleCol: 'Vehicle',
    perDayRentCol: 'Per Day Rent',
    mountainRentCol: 'Mountain Rent',

    perDayRent: 'Per Day Rent',
    mountainRent: 'Mountain Rent',
    totalAmount: 'Total Amount',
    advancePaid: 'Less: Advance Paid',
    balanceDue: 'Balance Due',

    // Signatures
    customerSig: 'Customer Signature',
    authSig: 'Authorized Signatory',

    // Footer
    generatedBy: 'Generated by Tour Booking App on',

    termsHeader: 'Terms and Conditions',
    terms: [
      'This booking is subject to vehicle availability and confirmation.',
      'Advance payment is non-refundable in case of cancellation within 24 hours of departure.',
      'Toll, parking, and permit charges are excluded unless specified otherwise.',
      'Driver support (Batta) is included/excluded as per verbal agreement.',
      'Any damage to the vehicle by passengers will be charged accordingly.'
    ]
  },
  ta: {
    companyName: '',
    regdNo: '',
    address: '',
    email: '',
    phoneLabel: 'செல்',
    documentTitle: 'சுற்றுலா முன்பதிவு ஒப்பந்தம்',

    // Headers
    customerDetails: 'வாடிக்கையாளர் விவரங்கள்',
    tripOverview: 'பயண விவரங்கள்',
    busRates: 'பஸ் வாடகை விவரம்',
    paymentSummary: 'கட்டண விவரம்',
    notes: 'குறிப்புகள்',

    // Labels
    name: 'பெயர்',
    contact: 'தொடர்புக்கு',
    bookingDate: 'பதிவு தேதி',
    tripDate: 'பயண தேதி',
    places: 'செல்லும் இடங்கள்',
    vehicle: 'வாகனம்',
    passengers: 'பயணிகள்',
    bus: 'பஸ்',
    description: 'விவரம்',

    // Table
    vehicleCol: 'வாகனம்',
    perDayRentCol: 'ஒரு நாள் வாடகை',
    mountainRentCol: 'மலை வாடகை',

    perDayRent: 'ஒரு நாள் வாடகை',
    mountainRent: 'மலை வாடகை',
    totalAmount: 'மொத்த தொகை',
    advancePaid: 'முன்பணம்',
    balanceDue: 'மீதம்',

    // Signatures
    customerSig: 'வாடிக்கையாளர் கையொப்பம்',
    authSig: 'உரிமையாளர் கையொப்பம்',

    // Footer
    generatedBy: 'உருவாக்கிய தேதி',

    termsHeader: 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
    terms: [
      'வாகனத்தின் இருப்பு மற்றும் உறுதிப்படுத்தலுக்கு உட்பட்டது.',
      'புறப்படுவதற்கு 24 மணி நேரத்திற்கு முன் ரத்து செய்தால் முன்பணம் திரும்பப் பெறப்படாது.',
      'சுங்கச்சாவடி, பார்க்கிங் மற்றும் அனுமதி கட்டணங்கள் தனி.',
      'ஓட்டுநர் உதவித்தொகை (பட்டா) வாய்மொழி ஒப்பந்தத்தின் படி.',
      'பயணிகளால் வாகனத்திற்கு ஏதேனும் சேதம் ஏற்பட்டால் அதற்குரிய கட்டணம் வசூலிக்கப்படும்.'
    ]
  }
};

function generateHtml(data: AgreementData, lang: 'en' | 'ta', branding?: BrandingOptions): string {
  const R = RESOURCES[lang];

  // Resolve Branding with Fallbacks
  const coin = (v: string | undefined, fallback: string) => (v && v.trim().length > 0 ? v : fallback);

  const companyName = coin(branding?.companyName, '[YOUR COMPANY NAME]');
  const companyAddress = coin(branding?.address, '');
  const companyPhone = coin(branding?.phone, '-');
  const companyEmail = coin(branding?.email, '');

  const busRatesRows = data.useIndividualBusRates && data.busRates
    ? (data.busRates || []).map((rate, i) => `
        <tr>
          <td>${R.bus} ${i + 1}</td>
          <td class="amount-col">${formatMoney(rate.perDayRent)}</td>
          <td class="amount-col">${rate.includeMountainRent ? formatMoney(rate.mountainRent) : '-'}</td>
        </tr>
      `).join('')
    : `
        <tr>
            <td style="font-style: italic;">${data.busType} (${data.busCount || 1})</td>
            <td class="amount-col">${formatMoney(data.perDayRent)}</td>
            <td class="amount-col">${data.includeMountainRent ? formatMoney(data.mountainRent) : '-'}</td>
        </tr>
    `;

  const termsHtml = R.terms.map(t => `<li>${t}</li>`).join('');

  return `
<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${R.documentTitle}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+Tamil:wght@400;600;700&display=swap');
    @page { margin: 40px; } /* Safer margin for printing */
    body { 
      font-family: 'Helvetica Neue', 'Helvetica', 'Noto Sans Tamil', sans-serif;
      font-size: 12px;
      line-height: 1.6; /* Better readability */
      color: #333;
      margin: 0;
      padding: 0;
    }

    .container {
      /* Removed fixed border to avoid awkward page splits */
      /* min-height: 90vh; */
      padding: 0 10px;
    }

    /* Header */
    .header {
      text-align: center;
      margin-bottom: 30px;
      border-bottom: 3px double #1a365d; /* Professional finish */
      padding-bottom: 20px;
    }
    .company-name {
      font-size: 26px;
      font-weight: 800;
      text-transform: uppercase;
      color: #1a365d;
      margin-bottom: 8px;
    }
    .company-details {
      font-size: 12px;
      color: #444;
      line-height: 1.4;
    }
    
    .doc-title {
      font-size: 20px;
      font-weight: 700;
      text-align: center;
      margin: 20px 0 30px 0;
      text-transform: uppercase;
      letter-spacing: 1px;
      text-decoration: none;
      border-bottom: 1px solid #ccc;
      display: inline-block;
      padding-bottom: 5px;
    }
    .doc-title-container { text-align: center; } /* Helper to center inline-block */

    /* Sections */
    .section {
      margin-bottom: 25px; /* More breathing room */
      page-break-inside: avoid;
      break-inside: avoid;
    }
    .section-title {
      font-size: 14px;
      font-weight: 700;
      color: #1a365d;
      background-color: transparent;
      padding: 5px 0;
      border-bottom: 2px solid #e5e7eb;
      border-left: none; /* Cleaner look */
      margin-bottom: 12px;
      text-transform: uppercase;
    }

    /* Grid for details */
    .flex-row {
      display: flex;
      justify-content: space-between;
      gap: 40px;
      page-break-inside: avoid;
      break-inside: avoid;
      margin-bottom: 20px;
    }
    .flex-col {
      flex: 1;
    }

    .row {
      display: flex;
      margin-bottom: 8px;
      align-items: flex-start;
    }
    .label {
      font-weight: 600;
      width: 140px;
      color: #555;
      flex-shrink: 0;
    }
    .value {
      flex: 1;
      font-weight: 500;
      color: #000;
      word-wrap: break-word;
      overflow-wrap: anywhere; /* aggressively break long words/URLs */
      word-break: break-word;
    }

    /* Table */
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
      page-break-inside: avoid;
      break-inside: avoid;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1); /* Subtle depth */
    }
    th, td {
      border: 1px solid #e5e7eb;
      padding: 10px; /* More padding */
      text-align: left;
    }
    th {
      background-color: #f3f4f6;
      font-weight: 700;
      color: #374151;
      text-transform: uppercase;
      font-size: 11px;
    }
    .amount-col {
      text-align: right;
      font-family: 'Courier New', Courier, monospace; /* Align numbers better */
    }

    /* Payment Summary Box - Cleaner floating look */
    .payment-box {
      border: 1px solid #e5e7eb;
      background-color: #f9fafb;
      padding: 15px;
      width: 320px;
      margin-left: auto;
      page-break-inside: avoid;
      break-inside: avoid;
      border-radius: 4px;
    }
    .pay-row {
      display: flex;
      justify-content: space-between;
      margin-bottom: 8px;
    }
    .pay-row.total {
      border-top: 2px solid #d1d5db;
      padding-top: 8px;
      margin-top: 8px;
      font-weight: 800;
      font-size: 15px;
      color: #1a365d;
    }

    /* Footer Signatures - More space */
    .footer-sigs {
      margin-top: 60px;
      display: flex;
      justify-content: space-between;
      gap: 60px;
      page-break-inside: avoid;
      break-inside: avoid;
    }
    .signature-box {
      text-align: center;
      flex: 1;
    }
    .signature-line {
      border-top: 1px solid #000; 
      padding-top: 8px; 
      font-weight: 600; 
      font-size: 12px;
      margin-top: 50px; /* Space for signature */
    }

    .terms-and-signatures {
       page-break-inside: avoid;
       break-inside: avoid;
       margin-top: 30px;
    }

    .terms {
      margin-top: 20px;
      margin-bottom: 40px;
      font-size: 10px;
      color: #666;
      border-top: 1px solid #e5e7eb;
      padding-top: 15px;
      background-color: transparent; /* Remove background box */
      border: none;
    }
    .terms h4 {
      margin-bottom: 8px;
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      color: #333;
    }
    .terms ul {
      padding-left: 18px;
      margin: 0;
    }
    .terms li {
      margin-bottom: 4px;
    }

    .meta-footer {
      text-align: center;
      margin-top: 40px;
      font-size: 9px;
      color: #9ca3af;
      border-top: 1px solid #f3f4f6;
      padding-top: 10px;
    }
  </style>
</head>
<body>
  <div class="container">
    
    <div class="header">
      <div class="company-name">${companyName}</div>
      <div class="company-details">
        ${companyAddress}<br/>
        ${R.contact}: ${companyPhone} ${companyEmail ? '| ' + companyEmail : ''}
      </div>
    </div>

    <div class="doc-title-container">
        <div class="doc-title">${R.documentTitle}</div>
    </div>

    <div class="flex-row">
      <div class="flex-col section">
        <div class="section-title">${R.customerDetails}</div>
        <div class="row"><span class="label">${R.name}:</span> <span class="value">${data.customerName}</span></div>
        <div class="row"><span class="label">${R.contact}:</span> <span class="value">${data.phone}</span></div>
        <div class="row"><span class="label">${R.passengers}:</span> <span class="value">${data.passengers || '-'}</span></div>
      </div>
      <div class="flex-col section">
         <div class="section-title">${R.tripOverview}</div>
         <div class="row"><span class="label">${R.tripDate}:</span> <span class="value">${data.fromDate} to ${data.toDate}</span></div>
         <div class="row"><span class="label">${R.places}:</span> <span class="value">${data.placesToCover}</span></div>
         <div class="row"><span class="label">${R.vehicle}:</span> <span class="value">${data.busType} x ${data.busCount || 1}</span></div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">${R.busRates}</div>
      <table>
         <tr>
           <th>${data.useIndividualBusRates ? R.vehicleCol : R.description}</th>
           <th class="amount-col">${data.useIndividualBusRates ? R.perDayRentCol : R.perDayRent}</th>
           <th class="amount-col">${data.useIndividualBusRates ? R.mountainRentCol : R.mountainRent}</th>
         </tr>
         ${busRatesRows}
      </table>
    </div>

    <div class="section">
      <div class="section-title">${R.paymentSummary}</div>
      <div class="payment-box">
         <div class="pay-row">
           <span>${R.totalAmount}:</span>
           <span>${formatMoney(data.totalAmount)}</span>
         </div>
         <div class="pay-row">
           <span>${R.advancePaid}:</span>
           <span>${formatMoney(data.advancePaid)}</span>
         </div>
         <div class="pay-row total">
           <span>${R.balanceDue}:</span>
           <span>${formatMoney(data.balance)}</span>
         </div>
      </div>
    </div>

    ${data.notes ? `
    <div class="section">
      <div class="section-title">${R.notes}</div>
      <p>${data.notes}</p>
    </div>` : ''}

    <div class="terms-and-signatures">
      <div class="terms">
        <h4>${R.termsHeader}</h4>
        <ul>
          ${termsHtml}
        </ul>
      </div>

      <div class="footer-sigs">
         <div class="signature-box">
           <div class="signature-line">${R.customerSig}</div>
         </div>
         <div class="signature-box">
           <div class="signature-line">${R.authSig}</div>
         </div>
      </div>
    </div>

    <div class="meta-footer">
      ${R.generatedBy} ${new Date().toLocaleDateString(lang === 'ta' ? 'ta-IN' : 'en-IN')}
    </div>

  </div>
</body>
</html>
  `;
}

export async function generateAndSharePdf(data: AgreementResponse | AgreementDraft, lang: 'en' | 'ta' = 'en', branding?: BrandingOptions) {
  try {
    const normalized = normalize(data);
    const html = generateHtml(normalized, lang, branding);

    const { uri } = await Print.printToFileAsync({ html });

    if (Platform.OS === 'ios') {
      await Sharing.shareAsync(uri, { UTI: 'com.adobe.pdf', mimeType: 'application/pdf' });
    } else {
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Agreement PDF' });
    }
  } catch (error) {
    Alert.alert('Error', 'Failed to generate or share PDF');
    console.error(error);
  }
}
