import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Alert, Platform } from 'react-native';

import type { AgreementDraft } from '../types/agreement';
import type { AgreementResponse } from '../types/api';

type AgreementData = {
  customerName: string;
  phone: string;
  fromDate: string;
  toDate: string;
  busType: string;
  busCount: string | number | null;
  passengers: string | number | null;
  placesToCover: string;

  perDayRent: string | number | null;
  includeMountainRent: boolean;
  mountainRent: string | number | null;

  totalAmount: string | number | null;
  advancePaid: string | number | null;
  balance: string | number | null;

  notes?: string;

  // For individual rates
  useIndividualBusRates: boolean;
  busRates?: Array<{
    perDayRent: string | number | null;
    includeMountainRent: boolean;
    mountainRent: string | number | null;
  }> | null;
};

// Normalize data from Response or Draft
function normalize(data: AgreementResponse | AgreementDraft): AgreementData {
  if ('id' in data) {
    // It's a Response
    return {
      customerName: data.customerName,
      phone: data.phone,
      fromDate: data.fromDate,
      toDate: data.toDate,
      busType: data.busType,
      busCount: data.busCount,
      passengers: data.passengers,
      placesToCover: data.placesToCover,
      perDayRent: data.perDayRent,
      includeMountainRent: data.includeMountainRent,
      mountainRent: data.mountainRent,
      totalAmount: data.totalAmount,
      advancePaid: data.advancePaid,
      balance: data.balance,
      notes: data.notes,
      useIndividualBusRates: data.useIndividualBusRates,
      busRates: data.busRates,
    };
  } else {
    // It's a Draft
    return {
      customerName: data.customerName,
      phone: data.phone,
      fromDate: data.fromDate,
      toDate: data.toDate,
      busType: data.busType,
      busCount: data.busCount,
      passengers: data.passengers,
      placesToCover: data.placesToCover,
      perDayRent: data.perDayRent,
      includeMountainRent: data.includeMountainRent,
      mountainRent: data.mountainRent,
      totalAmount: data.totalAmount,
      advancePaid: data.advancePaid,
      balance: data.balance,
      notes: data.notes,
      useIndividualBusRates: data.useIndividualBusRates,
      busRates: data.individualBusRates,
    };
  }
}

function formatMoney(amount: string | number | null | undefined): string {
  if (amount == null || amount === '') return '-';
  const n = Number(amount);
  if (Number.isNaN(n)) return String(amount);
  return '₹' + n.toLocaleString('en-IN');
}

const RESOURCES = {
  en: {
    companyName: 'SRI SAI SENTHIL TOURIST & TRAVELS',
    regdNo: 'Regd. CST No. 2013/33/605/02020/GS',
    address: 'No. 59/7-1, TMS Complex, Sannasami Naidu Street, Dharmapuri - 636701',
    email: 'gomanravi@gmail.com',
    phoneLabel: 'Cell',
    documentTitle: 'TOUR BOOKING AGREEMENT',

    // Headers
    customerDetails: 'Customer Details',
    tripOverview: 'Trip Overview',
    busRates: 'Bus Rate Breakdown',
    paymentSummary: 'Payment Summary',
    notes: 'Special Notes',

    // Labels
    name: 'Name',
    contact: 'Contact',
    bookingDate: 'Booking Date',
    tripDate: 'Trip Date',
    places: 'Places',
    vehicle: 'Vehicle',
    passengers: 'Passengers',
    bus: 'Bus',

    // Table
    vehicleCol: 'Vehicle',
    perDayRentCol: 'Per Day Rent',
    mountainRentCol: 'Mountain Rent',

    perDayRent: 'Per Day Rent',
    mountainRent: 'Mountain Rent',
    totalAmount: 'Total Amount',
    advancePaid: 'Less: Advance Paid',
    balanceDue: 'Balance Due',

    // Signatures
    customerSig: 'Customer Signature',
    authSig: 'Authorized Signatory',

    // Footer
    generatedBy: 'Generated by Tour Booking App on',

    termsHeader: 'Terms and Conditions',
    terms: [
      'This booking is subject to vehicle availability and confirmation.',
      'Advance payment is non-refundable in case of cancellation within 24 hours of departure.',
      'Toll, parking, and permit charges are excluded unless specified otherwise.',
      'Driver support (Batta) is included/excluded as per verbal agreement.',
      'Any damage to the vehicle by passengers will be charged accordingly.'
    ]
  },
  ta: {
    companyName: 'ஸ்ரீ சாய் செந்தல் டூரிஸ்ட் & டிராவல்ஸ்',
    regdNo: 'Regd. CST No. 2013/33/605/02020/GS',
    address: 'நெ. 59/7-1, TMS காம்ப்ளக்ஸ், சின்னசாமி நாயுடு தெரு, தருமபுரி - 636701',
    email: 'gomanravi@gmail.com',
    phoneLabel: 'செல்',
    documentTitle: 'சுற்றுலா முன்பதிவு ஒப்பந்தம்',

    // Headers
    customerDetails: 'வாடிக்கையாளர் விவரங்கள்',
    tripOverview: 'பயண விவரங்கள்',
    busRates: 'பஸ் வாடகை விவரம்',
    paymentSummary: 'கட்டண விவரம்',
    notes: 'குறிப்புகள்',

    // Labels
    name: 'பெயர்',
    contact: 'தொடர்புக்கு',
    bookingDate: 'பதிவு தேதி',
    tripDate: 'பயண தேதி',
    places: 'செல்லும் இடங்கள்',
    vehicle: 'வாகனம்',
    passengers: 'பயணிகள்',
    bus: 'பஸ்',

    // Table
    vehicleCol: 'வாகனம்',
    perDayRentCol: 'ஒரு நாள் வாடகை',
    mountainRentCol: 'மலை வாடகை',

    perDayRent: 'ஒரு நாள் வாடகை',
    mountainRent: 'மலை வாடகை',
    totalAmount: 'மொத்த தொகை',
    advancePaid: 'முன்பணம்',
    balanceDue: 'மீதம்',

    // Signatures
    customerSig: 'வாடிக்கையாளர் கையொப்பம்',
    authSig: 'உரிமையாளர் கையொப்பம்',

    // Footer
    generatedBy: 'உருவாக்கிய தேதி',

    termsHeader: 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
    terms: [
      'வாகனத்தின் இருப்பு மற்றும் உறுதிப்படுத்தலுக்கு உட்பட்டது.',
      'புறப்படுவதற்கு 24 மணி நேரத்திற்கு முன் ரத்து செய்தால் முன்பணம் திரும்பப் பெறப்படாது.',
      'சுங்கச்சாவடி, பார்க்கிங் மற்றும் அனுமதி கட்டணங்கள் தனி.',
      'ஓட்டுநர் உதவித்தொகை (பட்டா) வாய்மொழி ஒப்பந்தத்தின் படி.',
      'பயணிகளால் வாகனத்திற்கு ஏதேனும் சேதம் ஏற்பட்டால் அதற்குரிய கட்டணம் வசூலிக்கப்படும்.'
    ]
  }
};

function generateHtml(data: AgreementData, lang: 'en' | 'ta'): string {
  const R = RESOURCES[lang];

  const busRatesRows = data.useIndividualBusRates && data.busRates
    ? data.busRates.map((rate, i) => `
        <tr>
          <td>${R.bus} ${i + 1}</td>
          <td>${formatMoney(rate.perDayRent)}</td>
          <td>${rate.includeMountainRent ? formatMoney(rate.mountainRent) : '-'}</td>
        </tr>
      `).join('')
    : `
        <tr>
            <td colspan="3" style="text-align: center; font-style: italic;">${lang === 'ta' ? 'நிலையான வாடகை' : 'Standard Rate Applied'}</td>
        </tr>
    `;

  // Calculate rent details for the summary table
  const rentBreakdownHtml = data.useIndividualBusRates
    ? ''
    : `
        <tr>
            <td><strong>${R.perDayRent}</strong></td>
            <td class="text-right">${formatMoney(data.perDayRent)}</td>
        </tr>
        ${data.includeMountainRent ? `
        <tr>
            <td><strong>${R.mountainRent}</strong></td>
            <td class="text-right">${formatMoney(data.mountainRent)}</td>
        </tr>
        ` : ''}
    `;

  const termsHtml = R.terms.map(t => `<li>${t}</li>`).join('');

  return `
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      @page { margin: 20px; }
      body { font-family: 'Helvetica', sans-serif; font-size: 12px; color: #333; line-height: 1.5; }
      
      .header { text-align: center; margin-bottom: 20px; padding: 20px; background-color: #fffde7; border: 1px solid #f0f0f0; border-radius: 8px; }
      .phone-line { text-align: right; font-weight: bold; font-size: 11px; margin-bottom: 5px; }
      .company-name { font-size: ${lang === 'ta' ? '24px' : '26px'}; font-weight: bold; color: #d32f2f; margin-bottom: 5px; text-transform: uppercase; letter-spacing: 1px; }
      .regd-no { font-weight: bold; font-size: 11px; margin-bottom: 5px; }
      .company-details { font-size: 11px; color: #000; font-weight: 600; }
      .email { font-weight: bold; margin-top: 3px; }
      
      .document-title { font-size: 16px; font-weight: bold; text-align: center; margin: 15px 0; text-decoration: underline; text-transform: uppercase; }

      .grid-container { display: flex; justify-content: space-between; margin-bottom: 15px; gap: 15px; }
      .box { flex: 1; border: 1px solid #777; padding: 10px; border-radius: 4px; }
      .box-title { font-size: 13px; font-weight: bold; border-bottom: 1px solid #ddd; margin-bottom: 8px; padding-bottom: 4px; color: #000; }
      
      .row { display: flex; justify-content: space-between; margin-bottom: 4px; }
      .label { font-weight: bold; color: #555; }
      .value { text-align: right; font-weight: 600; color: #000; }

      table { width: 100%; border-collapse: collapse; margin-top: 10px; margin-bottom: 15px; }
      th, td { border: 1px solid #999; padding: 6px; text-align: left; font-size: 11px; }
      th { background-color: #fce4ec; font-weight: bold; }
      .text-right { text-align: right; }
      .total-row td { background-color: #fce4ec; font-weight: bold; font-size: 13px; }

      .section-title { font-size: 13px; font-weight: bold; margin-top: 15px; margin-bottom: 5px; color: #d32f2f; border-bottom: 1px solid #eee; padding-bottom: 2px; }
      
      .terms { font-size: 10px; color: #444; text-align: justify; margin-top: 20px; border: 1px solid #eee; padding: 10px; background: #fafafa; }
      .terms ul, .terms ol { padding-left: 20px; margin: 5px 0 0 0; }
      
      .signatures { margin-top: 50px; display: flex; justify-content: space-between; page-break-inside: avoid; }
      .signature-box { text-align: center; width: 40%; }
      .signature-line { border-top: 1px solid #000; margin-top: 40px; padding-top: 5px; font-weight: bold; font-size: 11px; }
      
      .footer { text-align: center; font-size: 9px; color: #999; margin-top: 30px; }
    </style>
  </head>
  <body>
    
    <div class="header">
      <div class="phone-line">${R.phoneLabel}: 94438 49013, 94430 56816</div>
      <div class="company-name">${R.companyName}</div>
      <div class="regd-no">${R.regdNo}</div>
      <div class="company-details">${R.address}</div>
      <div class="company-details email">Email: ${R.email}</div>
    </div>

    <div class="document-title">${R.documentTitle}</div>

    <div class="grid-container">
      <div class="box">
        <div class="box-title">${R.customerDetails}</div>
        <div class="row"><span class="label">${R.name}:</span><span class="value">${data.customerName}</span></div>
        <div class="row"><span class="label">${R.contact}:</span><span class="value">${data.phone}</span></div>
        <div class="row"><span class="label">${R.bookingDate}:</span><span class="value">${new Date().toLocaleDateString()}</span></div>
      </div>
      <div class="box">
        <div class="box-title">${R.tripOverview}</div>
        <div class="row"><span class="label">${R.tripDate}:</span><span class="value">${data.fromDate} - ${data.toDate}</span></div>
        <div class="row"><span class="label">${R.places}:</span><span class="value">${data.placesToCover}</span></div>
        <div class="row"><span class="label">${R.vehicle}:</span><span class="value">${data.busType} (${data.busCount})</span></div>
        <div class="row"><span class="label">${R.passengers}:</span><span class="value">${data.passengers || '-'}</span></div>
      </div>
    </div>

    ${data.useIndividualBusRates && data.busRates ? `
    <div class="section-title">${R.busRates}</div>
    <table>
      <thead>
        <tr>
          <th>${R.vehicleCol}</th>
          <th>${R.perDayRentCol}</th>
          <th>${R.mountainRentCol}</th>
        </tr>
      </thead>
      <tbody>
        ${busRatesRows}
      </tbody>
    </table>
    ` : ''}

    <div class="section-title">${R.paymentSummary}</div>
    <table class="summary-table">
      <tbody>
        ${rentBreakdownHtml}
        <tr>
            <td><strong>${R.totalAmount}</strong></td>
            <td class="text-right"><strong>${formatMoney(data.totalAmount)}</strong></td>
        </tr>
        <tr>
            <td>${R.advancePaid}</td>
            <td class="text-right">${formatMoney(data.advancePaid)}</td>
        </tr>
        <tr class="total-row">
            <td>${R.balanceDue}</td>
            <td class="text-right">${formatMoney(data.balance)}</td>
        </tr>
      </tbody>
    </table>

    ${data.notes ? `
    <div class="section-title">${R.notes}</div>
    <div style="border: 1px solid #ccc; padding: 10px; font-style: italic; font-size: 11px;">
      ${data.notes}
    </div>
    ` : ''}

    <div class="terms">
      <strong>${R.termsHeader}</strong>
      <ol>
        ${termsHtml}
      </ol>
    </div>

    <div class="signatures">
      <div class="signature-box">
        <div class="signature-line">${R.customerSig}</div>
      </div>
      <div class="signature-box">
        <div class="signature-line">${R.authSig}</div>
      </div>
    </div>

    <div class="footer">
      ${R.generatedBy} ${new Date().toLocaleString()}
    </div>
  </body>
</html>
  `;
}

export async function generateAndSharePdf(data: AgreementResponse | AgreementDraft, lang: 'en' | 'ta' = 'en') {
  try {
    const normalized = normalize(data);
    const html = generateHtml(normalized, lang);

    const { uri } = await Print.printToFileAsync({ html });

    if (Platform.OS === 'ios') {
      await Sharing.shareAsync(uri, { UTI: 'com.adobe.pdf', mimeType: 'application/pdf' });
    } else {
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Agreement PDF' });
    }
  } catch (error) {
    Alert.alert('Error', 'Failed to generate or share PDF');
    console.error(error);
  }
}
